name: Newman Tests
on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [local, prod]  # List your environments here
        collection: [restfull_booker_collection]  # List your collections here
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node
        uses: actions/setup-node@v2
        with: 
          node-version: '16.x'

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for Results
        run: mkdir -p reports

      - name: Run API Tests
        run: |
          newman run collections/${{ matrix.collection }}.json \
          -e environments/${{ matrix.environment }}_environment.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export reports/${{ matrix.collection }}_${{ matrix.environment }}_report.html

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with: 
          name: RunReports-${{ matrix.collection }}-${{ matrix.environment }}
          path: reports/${{ matrix.collection }}_${{ matrix.environment }}_report.html
